### ISSUE TITLE
Unable to download available package

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#58] opened 2016-08-15 15:49 UTC
Appears we have a package, `ipython_genutils`, that cannot be downloaded. This occurs in spite of the fact that there are packages available for it and it has been downloaded previously. More details in issue ( https://github.com/conda-forge/ipython_genutils-feedstock/issues/1 ) at the feedstock.

**Comment by dsludwig** [comment] 2016-08-15 16:55
Hi @jakirkham, it looks like this is caused by a bug we had for a brief window, where the metadata of packages would be altered incorrectly when a new file was uploaded. The result was the package would not be marked as a conda package, and so not available for download via the conda API (repodata.json, etc). You can see this is the case by the "All" in the breadcrumb:

<img width="731" alt="screen shot 2016-08-15 at 9 44 36 am" src="https://cloud.githubusercontent.com/assets/787031/17671643/ebe28d64-62cc-11e6-82ab-ce500c531f96.png">

Compare to a package with the correct metadata:

<img width="680" alt="screen shot 2016-08-15 at 9 45 08 am" src="https://cloud.githubusercontent.com/assets/787031/17671659/06a43bb6-62cd-11e6-97d0-fcac6b470a02.png">

To fix it, uploading a file to the package will cause the metadata to be updated correctly.

We thought we had caught and rolled this one back before anyone's packages were affected, but it looks like we were wrong - I've brought it up with the team to go over this, to see if we can find and repair any others.

**Comment by jakirkham** [comment] 2016-08-18 15:14
Another case of this is `docutils` at `conda-forge`.

**Comment by dsludwig** [comment] 2016-08-23 22:05
Hi @jakirkham, we rolled out a fix for this today, and I confirmed that I was able to install both `docutils` and `ipython_genutils` from `conda-forge`.

Thanks for the bug report, and please let me know if you encounter this again!

**Closed by dsludwig** 2016-08-23 22:05 UTC

**Comment by jakirkham** [comment] 2016-08-24 19:06
Nice! Thanks @dsludwig. Just tested this as well and it seems to be working for me too. Thanks for getting this one resolved.
