### ISSUE TITLE
Duplicate files with inconsistent checksums allowed on anaconda.org

### ISSUE THREAD

**Issue by hajapy** [Anaconda-Platform/support#95] opened 2017-02-07 14:04 UTC
The following files are duplicated in the conda-forge/marshmallow package:

linux-64/marshmallow-2.10.4-py35_0.tar.bz2
linux-64/marshmallow-2.10.4-py34_0.tar.bz2
linux-64/marshmallow-2.10.4-py27_0.tar.bz2

https://anaconda.org/conda-forge/marshmallow/files

There was an issue with the marshmallow-feedstock (https://github.com/conda-forge/marshmallow-feedstock/issues/7) that gave it multiple circleci webhooks, and thus multiple concurrent builds seem to have tried uploading their linux-64 builds to anaconda.org simultaneously. This race condition apparently allowed two same-name files to be uploaded with one having a valid MD5 checksum and another not. This also caused conda to hang when trying to install this version of marshmallow.

**Comment by jakirkham** [comment] 2017-05-02 05:12
Seems like a duplicate of issue ( https://github.com/ContinuumIO/anaconda-issues/issues/1607 ) possibly.

**Comment by koverholt** [comment] 2017-11-29 18:43
Issue moved to [Anaconda-Platform/anaconda-server #4792](https://github.com/Anaconda-Platform/anaconda-server/issues/4792) via [**ZenHub**](https://www.zenhub.com/)

**Closed by koverholt** 2017-11-29 18:43 UTC
