### ISSUE TITLE
Downloads badge displays 0k in case of more than 1000 downloads

### ISSUE THREAD

**Issue by kalefranz** [Anaconda-Platform/support#46] opened 2016-06-21 05:07 UTC
_From @johanneskoester on June 17, 2016 11:48_

As the title says. See here:

[![Anaconda-Server Badge](https://anaconda.org/bioconda/snakemake/badges/downloads.svg)](https://anaconda.org/bioconda/snakemake)

_Copied from original issue: ContinuumIO/anaconda-issues#829_

**Comment by jakirkham** [comment] 2016-07-15 20:41
Yep, agreed. Have seen this too. Would be nice to fix.

**Comment by stephenakearns** [comment] 2016-07-19 14:39
duplicate of #42  - closing this one and keeping 42 open. 

cc: @kalefranz @jakirkham

**Closed by stephenakearns** 2016-07-19 14:39 UTC
Labels: bug, Severity 4 - Low
